### ISSUE TITLE
CHECK_TYPE doesn't check const for function parameters

### ISSUE THREAD

**Issue by nahumj** [mercere99/Emperfect#4]
Example if the test case contains:
```
CHECK_TYPE(SharedLetters, std::string(std::string const &, std::string const, std::string const * const));
```

And the solution declares this function (note the second parameter):
```
std::string SharedLetters(std::string const & a, std::string b, std::string const * const ptr_c)
```
The test case passes regardless.

**Comment by mercere99** [comment]
I think the issue is that C++ doesn't differentiate const-ness (externally) of non-reference, non-pointer function parameters.  The `const` keyword in a function parameter promises that the variable you pass in won't be changed, but if you pass by value that's implicitly guaranteed...
